version: '3'

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: iTeacher-app
    ports:
      - '3000:3000'
      - '5555:5555'
      - '9229:9229'
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    build: .docker/postgres
    container_name: iTeacher-db
    restart: always
    tty: true
    ports:
      - '5432:5432'
    volumes:
      - .docker/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=iTeacher

  pgadmin:
    image: dpage/pgadmin4
    container_name: iTeacher-pgadmin
    restart: always
    ports:
      - '5050:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - db
